package patientflowmonitoring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-07-27T01:24:17.039-04:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://patientflowmonitoring/", name = "PFMServerService")
@XmlSeeAlso({ObjectFactory.class})
public interface PFMServerService {

    @WebResult(name = "PatientRegisteredResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientRegistered", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientRegistered")
    @WebMethod
    @ResponseWrapper(localName = "patientRegisteredResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientRegisteredResponse")
    public java.lang.String patientRegistered(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "roomId", targetNamespace = "")
        java.lang.String roomId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "RequestReferralResponse", targetNamespace = "")
    @RequestWrapper(localName = "requestReferral", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.RequestReferral")
    @WebMethod
    @ResponseWrapper(localName = "requestReferralResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.RequestReferralResponse")
    public java.lang.String requestReferral(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "referralType", targetNamespace = "")
        java.lang.String referralType,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "DischargeCompletedResponse", targetNamespace = "")
    @RequestWrapper(localName = "dischargeCompleted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.DischargeCompleted")
    @WebMethod
    @ResponseWrapper(localName = "dischargeCompletedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.DischargeCompletedResponse")
    public java.lang.String dischargeCompleted(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "WaitForProceduresResponse", targetNamespace = "")
    @RequestWrapper(localName = "waitForProcedures", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForProcedures")
    @WebMethod
    @ResponseWrapper(localName = "waitForProceduresResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForProceduresResponse")
    public java.lang.String waitForProcedures(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ConsultationCompleted2Response", targetNamespace = "")
    @RequestWrapper(localName = "consultationCompleted2", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationCompleted2")
    @WebMethod
    @ResponseWrapper(localName = "consultationCompleted2Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationCompleted2Response")
    public java.lang.String consultationCompleted2(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientAdmittedWithBedResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientAdmittedWithBed", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientAdmittedWithBed")
    @WebMethod
    @ResponseWrapper(localName = "patientAdmittedWithBedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientAdmittedWithBedResponse")
    public java.lang.String patientAdmittedWithBed(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientInCWResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientInCW", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientInCW")
    @WebMethod
    @ResponseWrapper(localName = "patientInCWResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientInCWResponse")
    public java.lang.String patientInCW(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ConsultationStarted1Response", targetNamespace = "")
    @RequestWrapper(localName = "consultationStarted1", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationStarted1")
    @WebMethod
    @ResponseWrapper(localName = "consultationStarted1Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationStarted1Response")
    public java.lang.String consultationStarted1(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientOutCCLResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientOutCCL", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientOutCCL")
    @WebMethod
    @ResponseWrapper(localName = "patientOutCCLResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientOutCCLResponse")
    public java.lang.String patientOutCCL(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PhysicianInCWResponse", targetNamespace = "")
    @RequestWrapper(localName = "physicianInCW", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianInCW")
    @WebMethod
    @ResponseWrapper(localName = "physicianInCWResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianInCWResponse")
    public java.lang.String physicianInCW(
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ProcedureStartedResponse", targetNamespace = "")
    @RequestWrapper(localName = "procedureStarted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProcedureStarted")
    @WebMethod
    @ResponseWrapper(localName = "procedureStartedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProcedureStartedResponse")
    public java.lang.String procedureStarted(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "procedureType", targetNamespace = "")
        java.lang.String procedureType,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ProcedureUpdatedResponse", targetNamespace = "")
    @RequestWrapper(localName = "procedureUpdated", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProcedureUpdated")
    @WebMethod
    @ResponseWrapper(localName = "procedureUpdatedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProcedureUpdatedResponse")
    public java.lang.String procedureUpdated(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "procedureType", targetNamespace = "")
        java.lang.String procedureType,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.String status,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ConsultationCompleted1Response", targetNamespace = "")
    @RequestWrapper(localName = "consultationCompleted1", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationCompleted1")
    @WebMethod
    @ResponseWrapper(localName = "consultationCompleted1Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationCompleted1Response")
    public java.lang.String consultationCompleted1(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientInEDResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientInED", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientInED")
    @WebMethod
    @ResponseWrapper(localName = "patientInEDResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientInEDResponse")
    public java.lang.String patientInED(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "WaitForTransportResponse", targetNamespace = "")
    @RequestWrapper(localName = "waitForTransport", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForTransport")
    @WebMethod
    @ResponseWrapper(localName = "waitForTransportResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForTransportResponse")
    public java.lang.String waitForTransport(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "OrdersExecutionCompletedResponse", targetNamespace = "")
    @RequestWrapper(localName = "ordersExecutionCompleted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.OrdersExecutionCompleted")
    @WebMethod
    @ResponseWrapper(localName = "ordersExecutionCompletedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.OrdersExecutionCompletedResponse")
    public java.lang.String ordersExecutionCompleted(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PhysicianInEDResponse", targetNamespace = "")
    @RequestWrapper(localName = "physicianInED", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianInED")
    @WebMethod
    @ResponseWrapper(localName = "physicianInEDResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianInEDResponse")
    public java.lang.String physicianInED(
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "pingResponse", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.Ping")
    @WebMethod
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PingResponse")
    public java.lang.String ping(
        @WebParam(name = "message", targetNamespace = "")
        java.lang.String message
    );

    @WebResult(name = "WaitForOrderExecutionResponse", targetNamespace = "")
    @RequestWrapper(localName = "waitForOrderExecution", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForOrderExecution")
    @WebMethod
    @ResponseWrapper(localName = "waitForOrderExecutionResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForOrderExecutionResponse")
    public java.lang.String waitForOrderExecution(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientOutEDResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientOutED", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientOutED")
    @WebMethod
    @ResponseWrapper(localName = "patientOutEDResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientOutEDResponse")
    public java.lang.String patientOutED(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientTransportRequestResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientTransportRequest", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientTransportRequest")
    @WebMethod
    @ResponseWrapper(localName = "patientTransportRequestResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientTransportRequestResponse")
    public java.lang.String patientTransportRequest(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ConsultationStarted2Response", targetNamespace = "")
    @RequestWrapper(localName = "consultationStarted2", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationStarted2")
    @WebMethod
    @ResponseWrapper(localName = "consultationStarted2Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationStarted2Response")
    public java.lang.String consultationStarted2(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ProcedureCompletedResponse", targetNamespace = "")
    @RequestWrapper(localName = "procedureCompleted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProcedureCompleted")
    @WebMethod
    @ResponseWrapper(localName = "procedureCompletedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProcedureCompletedResponse")
    public java.lang.String procedureCompleted(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "procedureType", targetNamespace = "")
        java.lang.String procedureType,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ProceduresExecutionCompletedResponse", targetNamespace = "")
    @RequestWrapper(localName = "proceduresExecutionCompleted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProceduresExecutionCompleted")
    @WebMethod
    @ResponseWrapper(localName = "proceduresExecutionCompletedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProceduresExecutionCompletedResponse")
    public java.lang.String proceduresExecutionCompleted(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ConsultationStarted3Response", targetNamespace = "")
    @RequestWrapper(localName = "consultationStarted3", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationStarted3")
    @WebMethod
    @ResponseWrapper(localName = "consultationStarted3Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationStarted3Response")
    public java.lang.String consultationStarted3(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientOutCWResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientOutCW", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientOutCW")
    @WebMethod
    @ResponseWrapper(localName = "patientOutCWResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientOutCWResponse")
    public java.lang.String patientOutCW(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "WaitForConsultation2Response", targetNamespace = "")
    @RequestWrapper(localName = "waitForConsultation2", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForConsultation2")
    @WebMethod
    @ResponseWrapper(localName = "waitForConsultation2Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForConsultation2Response")
    public java.lang.String waitForConsultation2(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "BedRequestResponse", targetNamespace = "")
    @RequestWrapper(localName = "bedRequest", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedRequest")
    @WebMethod
    @ResponseWrapper(localName = "bedRequestResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedRequestResponse")
    public java.lang.String bedRequest(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "WaitForConsultation1Response", targetNamespace = "")
    @RequestWrapper(localName = "waitForConsultation1", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForConsultation1")
    @WebMethod
    @ResponseWrapper(localName = "waitForConsultation1Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForConsultation1Response")
    public java.lang.String waitForConsultation1(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientInCCLResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientInCCL", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientInCCL")
    @WebMethod
    @ResponseWrapper(localName = "patientInCCLResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientInCCLResponse")
    public java.lang.String patientInCCL(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "BedCleanUpRequestResponse", targetNamespace = "")
    @RequestWrapper(localName = "bedCleanUpRequest", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedCleanUpRequest")
    @WebMethod
    @ResponseWrapper(localName = "bedCleanUpRequestResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedCleanUpRequestResponse")
    public java.lang.String bedCleanUpRequest(
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PhysicianOutCWResponse", targetNamespace = "")
    @RequestWrapper(localName = "physicianOutCW", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianOutCW")
    @WebMethod
    @ResponseWrapper(localName = "physicianOutCWResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianOutCWResponse")
    public java.lang.String physicianOutCW(
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "BedCleanUpStartedResponse", targetNamespace = "")
    @RequestWrapper(localName = "bedCleanUpStarted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedCleanUpStarted")
    @WebMethod
    @ResponseWrapper(localName = "bedCleanUpStartedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedCleanUpStartedResponse")
    public java.lang.String bedCleanUpStarted(
        @WebParam(name = "houseKeepingId", targetNamespace = "")
        java.lang.String houseKeepingId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "BedCleanUpCompletedResponse", targetNamespace = "")
    @RequestWrapper(localName = "bedCleanUpCompleted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedCleanUpCompleted")
    @WebMethod
    @ResponseWrapper(localName = "bedCleanUpCompletedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.BedCleanUpCompletedResponse")
    public java.lang.String bedCleanUpCompleted(
        @WebParam(name = "houseKeepingId", targetNamespace = "")
        java.lang.String houseKeepingId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientArrivedInBedResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientArrivedInBed", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientArrivedInBed")
    @WebMethod
    @ResponseWrapper(localName = "patientArrivedInBedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientArrivedInBedResponse")
    public java.lang.String patientArrivedInBed(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientTransportStartedResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientTransportStarted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientTransportStarted")
    @WebMethod
    @ResponseWrapper(localName = "patientTransportStartedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientTransportStartedResponse")
    public java.lang.String patientTransportStarted(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "WaitForBedResponse", targetNamespace = "")
    @RequestWrapper(localName = "waitForBed", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForBed")
    @WebMethod
    @ResponseWrapper(localName = "waitForBedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForBedResponse")
    public java.lang.String waitForBed(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ConsultationCompleted3Response", targetNamespace = "")
    @RequestWrapper(localName = "consultationCompleted3", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationCompleted3")
    @WebMethod
    @ResponseWrapper(localName = "consultationCompleted3Response", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ConsultationCompleted3Response")
    public java.lang.String consultationCompleted3(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "WaitForBedCleanUpResponse", targetNamespace = "")
    @RequestWrapper(localName = "waitForBedCleanUp", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForBedCleanUp")
    @WebMethod
    @ResponseWrapper(localName = "waitForBedCleanUpResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForBedCleanUpResponse")
    public java.lang.String waitForBedCleanUp(
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "triageScoreResponse", targetNamespace = "")
    @RequestWrapper(localName = "triageScore", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.TriageScore")
    @WebMethod
    @ResponseWrapper(localName = "triageScoreResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.TriageScoreResponse")
    public java.lang.String triageScore(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "ctas", targetNamespace = "")
        java.lang.String ctas,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "ProceduresScheduledResponse", targetNamespace = "")
    @RequestWrapper(localName = "proceduresScheduled", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProceduresScheduled")
    @WebMethod
    @ResponseWrapper(localName = "proceduresScheduledResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.ProceduresScheduledResponse")
    public java.lang.String proceduresScheduled(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "procedureScheduledTime", targetNamespace = "")
        java.lang.String procedureScheduledTime,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "OrderRequestResponse", targetNamespace = "")
    @RequestWrapper(localName = "orderRequest", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.OrderRequest")
    @WebMethod
    @ResponseWrapper(localName = "orderRequestResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.OrderRequestResponse")
    public java.lang.String orderRequest(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "orderType", targetNamespace = "")
        java.lang.String orderType,
        @WebParam(name = "orderId", targetNamespace = "")
        java.lang.String orderId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "OrderRequestCompletedResponse", targetNamespace = "")
    @RequestWrapper(localName = "orderRequestCompleted", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.OrderRequestCompleted")
    @WebMethod
    @ResponseWrapper(localName = "orderRequestCompletedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.OrderRequestCompletedResponse")
    public java.lang.String orderRequestCompleted(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "orderType", targetNamespace = "")
        java.lang.String orderType,
        @WebParam(name = "orderId", targetNamespace = "")
        java.lang.String orderId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "DischargeRequestResponse", targetNamespace = "")
    @RequestWrapper(localName = "dischargeRequest", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.DischargeRequest")
    @WebMethod
    @ResponseWrapper(localName = "dischargeRequestResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.DischargeRequestResponse")
    public java.lang.String dischargeRequest(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "providerId", targetNamespace = "")
        java.lang.String providerId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "HouseKeepingnInCWResponse", targetNamespace = "")
    @RequestWrapper(localName = "houseKeepingInCW", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.HouseKeepingInCW")
    @WebMethod
    @ResponseWrapper(localName = "houseKeepingInCWResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.HouseKeepingInCWResponse")
    public java.lang.String houseKeepingInCW(
        @WebParam(name = "houseKeepingId", targetNamespace = "")
        java.lang.String houseKeepingId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PatientAdmittedWithNoBedResponse", targetNamespace = "")
    @RequestWrapper(localName = "patientAdmittedWithNoBed", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientAdmittedWithNoBed")
    @WebMethod
    @ResponseWrapper(localName = "patientAdmittedWithNoBedResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PatientAdmittedWithNoBedResponse")
    public java.lang.String patientAdmittedWithNoBed(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "HouseKeepingOutCWResponse", targetNamespace = "")
    @RequestWrapper(localName = "houseKeepingOutCW", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.HouseKeepingOutCW")
    @WebMethod
    @ResponseWrapper(localName = "houseKeepingOutCWResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.HouseKeepingOutCWResponse")
    public java.lang.String houseKeepingOutCW(
        @WebParam(name = "houseKeepingId", targetNamespace = "")
        java.lang.String houseKeepingId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "PhysicianOutEDResponse", targetNamespace = "")
    @RequestWrapper(localName = "physicianOutED", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianOutED")
    @WebMethod
    @ResponseWrapper(localName = "physicianOutEDResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.PhysicianOutEDResponse")
    public java.lang.String physicianOutED(
        @WebParam(name = "physicianId", targetNamespace = "")
        java.lang.String physicianId,
        @WebParam(name = "locationId", targetNamespace = "")
        java.lang.String locationId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );

    @WebResult(name = "WaitForDischargeResponse", targetNamespace = "")
    @RequestWrapper(localName = "waitForDischarge", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForDischarge")
    @WebMethod
    @ResponseWrapper(localName = "waitForDischargeResponse", targetNamespace = "http://patientflowmonitoring/", className = "patientflowmonitoring.WaitForDischargeResponse")
    public java.lang.String waitForDischarge(
        @WebParam(name = "patientId", targetNamespace = "")
        java.lang.String patientId,
        @WebParam(name = "unitId", targetNamespace = "")
        java.lang.String unitId,
        @WebParam(name = "timestamp", targetNamespace = "")
        java.lang.String timestamp
    );
}
