package patientflowmonitoring;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-07-27T01:24:17.185-04:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "PFMServerServiceService", 
                  wsdlLocation = "web-app/PFMServer.wsdl",
                  targetNamespace = "http://patientflowmonitoring/") 
public class PFMServerServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://patientflowmonitoring/", "PFMServerServiceService");
    public final static QName PFMServerServicePort = new QName("http://patientflowmonitoring/", "PFMServerServicePort");
    static {
        URL url = PFMServerServiceService.class.getResource("web-app/PFMServer.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PFMServerServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "web-app/PFMServer.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public PFMServerServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PFMServerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PFMServerServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PFMServerService
     */
    @WebEndpoint(name = "PFMServerServicePort")
    public PFMServerService getPFMServerServicePort() {
        return super.getPort(PFMServerServicePort, PFMServerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PFMServerService
     */
    @WebEndpoint(name = "PFMServerServicePort")
    public PFMServerService getPFMServerServicePort(WebServiceFeature... features) {
        return super.getPort(PFMServerServicePort, PFMServerService.class, features);
    }

}
